title: Rounding a number with Python
hero_image: images/banner.png
description: Find out how to round a number
original_url:
theme: cc-prototype
duration: 1 # 1, 2 or 3
listed: false
ingredient: true
copyedit: false
interests: ""
technologies: "python"
steps:
  - title: Rounding a number
